package Calc;


/**
* Calc/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Sunday, April 1, 2018 8:00:32 PM VET
*/

public interface CalculatorOperations 
{
  String add (double x, double y);
  String subtract (double a, double b);
  String multiply (double x, double y);
  String divide (double a, double b);
  String random ();
  void shutdown ();
} // interface CalculatorOperations
