package Calc;

/**
* Calc/CalculatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Sunday, April 1, 2018 8:00:32 PM VET
*/

public final class CalculatorHolder implements org.omg.CORBA.portable.Streamable
{
  public Calc.Calculator value = null;

  public CalculatorHolder ()
  {
  }

  public CalculatorHolder (Calc.Calculator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Calc.CalculatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Calc.CalculatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Calc.CalculatorHelper.type ();
  }

}
