package Calculator;


/**
* Calculator/CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Sunday, April 1, 2018 6:33:08 PM VET
*/

public interface CalcOperations 
{
  float sum (float x, float y);
  float rest (float x, float y);
  float mult (float x, float y);
  float divi (float x, float y);
  float pot (float x, float y);
  float square (float x, float y);
  void shutdown ();
} // interface CalcOperations
