package Calculator;


/**
* Calculator/CalcPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Sunday, April 1, 2018 6:33:08 PM VET
*/

public abstract class CalcPOA extends org.omg.PortableServer.Servant
 implements Calculator.CalcOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sum", new java.lang.Integer (0));
    _methods.put ("rest", new java.lang.Integer (1));
    _methods.put ("mult", new java.lang.Integer (2));
    _methods.put ("divi", new java.lang.Integer (3));
    _methods.put ("pot", new java.lang.Integer (4));
    _methods.put ("square", new java.lang.Integer (5));
    _methods.put ("shutdown", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Calculator/Calc/sum
       {
         float x = in.read_float ();
         float y = in.read_float ();
         float $result = (float)0;
         $result = this.sum (x, y);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 1:  // Calculator/Calc/rest
       {
         float x = in.read_float ();
         float y = in.read_float ();
         float $result = (float)0;
         $result = this.rest (x, y);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 2:  // Calculator/Calc/mult
       {
         float x = in.read_float ();
         float y = in.read_float ();
         float $result = (float)0;
         $result = this.mult (x, y);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 3:  // Calculator/Calc/divi
       {
         float x = in.read_float ();
         float y = in.read_float ();
         float $result = (float)0;
         $result = this.divi (x, y);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 4:  // Calculator/Calc/pot
       {
         float x = in.read_float ();
         float y = in.read_float ();
         float $result = (float)0;
         $result = this.pot (x, y);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 5:  // Calculator/Calc/square
       {
         float x = in.read_float ();
         float y = in.read_float ();
         float $result = (float)0;
         $result = this.square (x, y);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 6:  // Calculator/Calc/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Calculator/Calc:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Calc _this() 
  {
    return CalcHelper.narrow(
    super._this_object());
  }

  public Calc _this(org.omg.CORBA.ORB orb) 
  {
    return CalcHelper.narrow(
    super._this_object(orb));
  }


} // class CalcPOA
